name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Boost
      run: |
        brew update
        brew install boost
      
    - name: Install openssl
      run: brew reinstall openssl@1.1

    - name: Set Root DIR
      run: OPENSSL_ROOT_DIR=$(brew --prefix openssl)

    - name: Removing existing build DIR
      run: |
        rm -r ${{github.workspace}}/build
        mkdir ${{github.workspace}}/build
      
    - name: Create Cmake files
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

